# Generated by Django 3.0.5 on 2020-04-22 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('part', models.CharField(choices=[('chest', '胸'), ('shoulder', '肩'), ('arm', '腕'), ('leg', '足'), ('back', '背中'), ('abdomen', '腹')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('times', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muscle.Menu')),
            ],
        ),
    ]
