# Generated by Django 3.0.4 on 2020-04-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0002_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
