# Generated by Django 3.0.4 on 2020-04-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0002_auto_20200413_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
    ]
