# Generated by Django 3.0.4 on 2020-04-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0003_auto_20200413_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part',
            new_name='name',
        ),
    ]
