# Generated by Django 3.0.4 on 2020-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0004_auto_20200413_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='part',
            field=models.CharField(choices=[('chest', '胸'), ('shoulder', '肩'), ('arm', '腕'), ('leg', '足'), ('back', '背中'), ('abdomen', '腹')], max_length=8),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
